#!/usr/bin/env python3
"""Generate the full native diagnostic matrix from the pending release workflow.

Validation is copied verbatim except for the semantic-release skip condition;
publication is replaced wholesale with a local-only receipt/promotion probe.
Do not dispatch until the accepted baseline and matching detectors exist.
"""
import argparse
import hashlib
from pathlib import Path

HERE = Path(__file__).resolve().parent
TARGET = HERE.parents[2] / '.github/workflows/soak-release-proof.yml'

HEADER = '''name: Full release validation proof (no publication)

on:
  workflow_dispatch:
  push:
    tags:
      - 'soak-release-proof-*'

permissions:
  contents: read

jobs:
'''

PUBLISHER = '''
  publication-stub:
    name: Full receipt publication stub (no provider calls)
    needs: validation
    runs-on: ubuntu-24.04
    timeout-minutes: 20
    concurrency:
      group: quick-release-diagnostic-publication
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
      - uses: actions/download-artifact@v4.3.0
        with:
          name: release-soak-${{ github.sha }}-${{ github.run_attempt }}
          path: tests/results/soak/downloaded-candidate
      - name: Verify the complete receipt and exercise local-only promotion
        env:
          CANDIDATE_SHA: ${{ github.sha }}
          HOLD_SECONDS: ${{ contains(github.ref_name, '-serialization-') && '180' || '0' }}
        run: |
          python3 tests/soak/release/probe_qualified.py \\
            --run tests/results/soak/downloaded-candidate/supervision/run \\
            --candidate "$CANDIDATE_SHA" \\
            --baseline tests/soak/baselines/lucee6-serial.json \\
            --output tests/results/soak/full-publication-proof \\
            --hold-seconds "$HOLD_SECONDS"
      - name: Retain local publication proof, including partial failures
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: full-publication-proof-${{ github.run_id }}
          path: tests/results/soak/full-publication-proof/
          if-no-files-found: error
          retention-days: 30
'''


def render(template):
    if template.count('\njobs:\n') != 1 or template.count('\n  release:\n') != 1:
        raise ValueError('Pending workflow structure changed; review probe generation')
    validation = template.split('\njobs:\n')[1].split('\n  release:\n')[0]
    skip = '    if: "!contains(github.event.head_commit.message, \'__SEMANTIC RELEASE VERSION UPDATE__\')"\n'
    if validation.count(skip) != 1:
        raise ValueError('Expected exactly one release-message skip condition')
    validation = validation.replace(skip, '')
    if validation.count('- kind: functional') != 23 or validation.count('- kind: soak') != 1:
        raise ValueError('Full proof requires all 23 functional rows and exactly one soak row')
    for forbidden in ('contents: write', 'FORGEBOX_TOKEN', 'promote_qualified.py'):
        if forbidden in validation:
            raise ValueError('Validation unexpectedly contains publisher capabilities')
    source_hash = hashlib.sha256(template.encode()).hexdigest()
    return '# Generated by tests/soak/release/stage_full_probe.py; do not edit.\n' + \
        '# Pending workflow SHA-256: ' + source_hash + '\n' + HEADER + validation + PUBLISHER


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Reject drift without rewriting')
    parser.add_argument('--output', type=Path, default=TARGET)
    args = parser.parse_args()
    content = render((HERE / 'release.yml.pending').read_text())
    if args.check:
        if args.output.read_text() != content:
            raise ValueError('Full diagnostic workflow differs from the pending release validation')
    else:
        args.output.write_text(content)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
